apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-calculator-app-exercise
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  # ignoreDifferences:
  #   - group: autoscaling
  #     kind: HorizontalPodAutoscaler
  #     jqPathExpressions:
  #       - .spec.metrics[].resource.name | select((. == "cpu") or (. == "memory"))
  destination:
    server: https://kubernetes.default.svc
    namespace: exercise 
  project: default
  source:
    path: helm-chart/application
    helm:
      releaseName: flask-calculator-app-exercise
      valueFiles:
      - ../../helm-values/flask-calculator-app/values-exercise.yaml
    repoURL: https://github.com/srijan-shukla/Kubernetes.git
    targetRevision: master
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true